/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import dbb.DBBroker;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Banka;
import model.Drzava;
import model.Mesto;

/**
 *
 * @author Marija
 */
public class FBanka extends javax.swing.JFrame {

    
    DBBroker dbb = new DBBroker();
    private Operacija operacija;

    public Operacija getOperacija() {
        return operacija;
    }

    private void popuniComboBoxDrzava() {
         try {
            cmbDrzava.removeAllItems();
            dbb.uspostaviKonekciju();
            List<Drzava> lista = dbb.vratiSveDrzave();
            dbb.potvrdiTransakciju();
            dbb.raskiniKonekciju();
            for (Drzava drzava : lista) {
                cmbDrzava.addItem(drzava);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FBanka.class.getName()).log(Level.SEVERE, null, ex);
            dbb.ponistiTransakciju();
            dbb.raskiniKonekciju();
        }
    }

    private void popuniComboBoxMesto() {
        try {
            cmbMesto.removeAllItems();
            dbb.uspostaviKonekciju();
            List<Mesto> lista = dbb.vratiSvaMesta();
            dbb.potvrdiTransakciju();
            dbb.raskiniKonekciju();
            for (Mesto m : lista) {
                cmbMesto.addItem(m);
            }
            ComboBoxModel model = new DefaultComboBoxModel(lista.toArray());
            cmbMesto.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FBanka.class.getName()).log(Level.SEVERE, null, ex);
            dbb.ponistiTransakciju();
            dbb.raskiniKonekciju();
        }
    }
    /**
     * Creates new form FIzvod
     */
    public enum Operacija {
        KREIRANJE,
        IZMENA
    }

    /**
     * Creates new form FNarudzbenica
     */
    public FBanka(String flag) {
        initComponents();

        if (flag.equals("kreiraj")) {
            operacija = Operacija.KREIRANJE;
            btnPronadji.setVisible(false);
            btnIzmeni.setVisible(false);
            btnObrisi.setVisible(false);
            popuniComboBoxDrzava();
            popuniComboBoxMesto();
            jtfDrzavaID.setEnabled(false);
            jtfMesrtoID.setEnabled(false);
            jtfNazivDrzave.setEnabled(false);
            jtfNazivMesta.setEnabled(false);
        }
        if (flag.equals("izmeni")) {
            operacija = Operacija.IZMENA;
            btnSacuvaj.setVisible(false);
            btnIzmeni.setEnabled(false);
            btnObrisi.setEnabled(false);
            jtfNazivBanke.setEnabled(false);
            cmbDrzava.setEnabled(false);
            cmbMesto.setEnabled(false);
            jtfDrzavaID.setEnabled(false);
            jtfMesrtoID.setEnabled(false);
            jtfNazivDrzave.setEnabled(false);
            jtfNazivMesta.setEnabled(false);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfBankaID = new javax.swing.JTextField();
        jtfNazivBanke = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbMesto = new javax.swing.JComboBox<Object>();
        cmbDrzava = new javax.swing.JComboBox<Object>();
        jLabel6 = new javax.swing.JLabel();
        btnPronadji = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jtfMesrtoID = new javax.swing.JTextField();
        jtfNazivMesta = new javax.swing.JTextField();
        jtfDrzavaID = new javax.swing.JTextField();
        jtfNazivDrzave = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("BankaID");

        jLabel2.setText("Naziv banke");

        jLabel5.setText("Mesto");

        jLabel6.setText("Drzava");

        btnPronadji.setText("Pronadji");
        btnPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPronadjiActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel7.setText("Naziv mesta");

        jLabel8.setText("MestoID");

        jLabel9.setText("Drzava ID");

        jLabel10.setText("Naziv drzave");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNazivBanke, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jtfBankaID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(btnPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfNazivMesta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfMesrtoID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfDrzavaID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfNazivDrzave, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBankaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPronadji)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jtfNazivBanke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMesrtoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNazivMesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDrzavaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNazivDrzave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIzmeni)
                        .addComponent(btnObrisi)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
            String bankaID = jtfBankaID.getText().trim();
            if (bankaID.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Niste popunili sva polja", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (!bankaID.matches("[1-9][0-9]*")) {
                JOptionPane.showMessageDialog(null, "ID mora da bude broj", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Banka b = new Banka();
            
            b.setBankaID(Integer.parseInt(bankaID));
            b.setNazivBanke(jtfNazivBanke.getText());
            b.setDrzavaID((Drzava) cmbDrzava.getSelectedItem());
            b.setMestoID((Mesto) cmbMesto.getSelectedItem());
            jtfDrzavaID.setText(b.getDrzavaID().getDrzavaID()+ "");
            jtfMesrtoID.setText(b.getMestoID().getMestoID() + "");
            jtfNazivDrzave.setText(b.getDrzavaID().getNazivDrzave());
            jtfNazivMesta.setText(b.getMestoID().getNazivMesta());
            
            try {
                dbb.uspostaviKonekciju();
                dbb.ubaciBanku(b);
                dbb.potvrdiTransakciju();
                dbb.raskiniKonekciju();
                JOptionPane.showMessageDialog(null, "Uspešno ubacen banka", "Banka", JOptionPane.INFORMATION_MESSAGE);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(FReklamacija.class.getName()).log(Level.SEVERE, null, ex);
                dbb.ponistiTransakciju();
                dbb.raskiniKonekciju();
                JOptionPane.showMessageDialog(null, "Neuspešno ubacivanje banke\n"+ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
            dispose();
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPronadjiActionPerformed
        try {     
            if (jtfBankaID.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Niste popunili sva polja za pretragu", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (!jtfBankaID.getText().matches("[1-9][0-9]*")) {
                JOptionPane.showMessageDialog(null, "ID mora da bude broj", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
              
            dbb.uspostaviKonekciju();
      
            Banka b = dbb.ucitajBanku(Integer.parseInt(jtfBankaID.getText()));
            if (b == null) {
                JOptionPane.showMessageDialog(null, "Nije pronadjen izvod sa datim rb", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            dbb.potvrdiTransakciju();
            dbb.raskiniKonekciju();
            jtfBankaID.setText(b.getBankaID()+"");
            jtfNazivBanke.setText(b.getNazivBanke());
            popuniComboBoxDrzava();
            popuniComboBoxMesto();
            for (int i = 0; i < cmbMesto.getItemCount(); i++) {
                if (cmbMesto.getItemAt(i).toString().equals(b.getMestoID().getNazivMesta())) {
                    System.out.println("pronasao mesto");
                    cmbMesto.setSelectedItem(cmbMesto.getItemAt(i));
                }
            }
            popuniComboBoxDrzava();
            for (int i = 0; i < cmbDrzava.getItemCount(); i++) {
                if (cmbDrzava.getItemAt(i).toString().equals(b.getDrzavaID().getNazivDrzave())) {
                    System.out.println("pronasao drzavu");
                    cmbDrzava.setSelectedItem(cmbDrzava.getItemAt(i));
                }
            }

            jtfDrzavaID.setText(b.getDrzavaID().getDrzavaID()+ "");
            jtfMesrtoID.setText(b.getMestoID().getMestoID() + "");
            jtfNazivDrzave.setText(b.getDrzavaID().getNazivDrzave());
            jtfNazivMesta.setText(b.getMestoID().getNazivMesta());
            jtfBankaID.setEnabled(false);
            btnPronadji.setEnabled(false);
            jtfNazivBanke.setEnabled(true);
            cmbMesto.setEnabled(true);
            cmbDrzava.setEnabled(true);
            btnIzmeni.setEnabled(true);
            btnObrisi.setEnabled(true);
            } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FBanka.class.getName()).log(Level.SEVERE, null, ex);
            dbb.ponistiTransakciju();
            dbb.raskiniKonekciju();
            JOptionPane.showMessageDialog(null, "Neuspešno pretrazivanje izvoda\n"+ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPronadjiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

            String bankaID = jtfBankaID.getText().trim();
            if (bankaID.isEmpty() ) {
                JOptionPane.showMessageDialog(null, "Niste popunili sva polja", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Banka b = new Banka();

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            b.setBankaID(Integer.parseInt(bankaID));
            b.setNazivBanke(jtfNazivBanke.getText());
            b.setMestoID((Mesto) cmbMesto.getSelectedItem());
            b.setDrzavaID((Drzava) cmbDrzava.getSelectedItem());
            jtfDrzavaID.setText(b.getDrzavaID().getDrzavaID()+ "");
            jtfMesrtoID.setText(b.getMestoID().getMestoID() + "");
            jtfNazivDrzave.setText(b.getDrzavaID().getNazivDrzave());
            jtfNazivMesta.setText(b.getMestoID().getNazivMesta());
            try {
                dbb.uspostaviKonekciju();
                dbb.izmeniBanku(b);
                dbb.potvrdiTransakciju();
                dbb.raskiniKonekciju();
                JOptionPane.showMessageDialog(null, "Uspešno izmenjen izvod", "Izmena", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Nije uspela izmena\n"+ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(FBanka.class.getName()).log(Level.SEVERE, null, ex);
                dbb.ponistiTransakciju();
                dbb.raskiniKonekciju();
            }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        String bankaID = jtfBankaID.getText().trim();

        if (bankaID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Niste popunili broj izvoda", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            dbb.uspostaviKonekciju();
            boolean uspesno = dbb.obrisiBanku(Integer.parseInt(bankaID));
            if (uspesno) {
                dbb.potvrdiTransakciju();
                dbb.raskiniKonekciju();
                JOptionPane.showMessageDialog(null, "Uspešno obrisana banka", "", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {
                dbb.ponistiTransakciju();
                dbb.raskiniKonekciju();
                JOptionPane.showMessageDialog(null, "Neuspešno obrisana banka", "Greška", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            dbb.ponistiTransakciju();
            dbb.raskiniKonekciju();
            JOptionPane.showMessageDialog(null, "Neuspešno brisanje banke\n"+ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FBanka.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPronadji;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Object> cmbDrzava;
    private javax.swing.JComboBox<Object> cmbMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfBankaID;
    private javax.swing.JTextField jtfDrzavaID;
    private javax.swing.JTextField jtfMesrtoID;
    private javax.swing.JTextField jtfNazivBanke;
    private javax.swing.JTextField jtfNazivDrzave;
    private javax.swing.JTextField jtfNazivMesta;
    // End of variables declaration//GEN-END:variables
}
